PROGRAM CIRCULAR_DISK
  IMPLICIT NONE
  INTEGER, PARAMETER :: NUM = 100000
  REAL(8), PARAMETER :: TWOPI = 8.0D0 * ATAN(1.0D0)
  INTEGER :: I
  REAL(8) :: VEC(2),X,THETA,MAG,AR1,AR2,AR

  AR1 = 1.0D0
  AR2 = 2.0D0
  DO I = 1, NUM
     CALL RANDOM_NUMBER(X)
     AR = AR1 + (AR2 - AR1) * X
     CALL RANDOM_NUMBER(X)
     THETA = X * TWOPI
     VEC(1) = AR * COS(THETA)
     VEC(2) = AR * SIN(THETA)
     WRITE(1,'(2(F15.10,1X))')VEC
  END DO

  DO I = 1, NUM
     CALL RANDOM_NUMBER(X)
     AR = AR1**2 + (AR2**2 - AR1**2) * X
     AR = SQRT(AR)
     CALL RANDOM_NUMBER(X)
     THETA = X * TWOPI
     VEC(1) = AR * COS(THETA)
     VEC(2) = AR * SIN(THETA)
     WRITE(2,'(2(F15.10,1X))')VEC
  END DO


END PROGRAM CIRCULAR_DISK
