PROGRAM MAIN
  IMPLICIT NONE

  REAL(8), CODIMENSION[*] :: X
  
  IF (THIS_IMAGE() == 1) THEN
     CALL RANDOM_NUMBER(X)
  END IF

  IF (THIS_IMAGE() == 2) THEN
     X = 2.0D0 * X[1]
  END IF
  SYNC ALL
  WRITE(*,*) "hELLO FROM IMAGE ", THIS_IMAGE(), "OUT OF ", NUM_IMAGES()," TOTAL IMAGES"
  WRITE(*,*) "X =", X[THIS_IMAGE()], 'FROM', THIS_IMAGE(), "OUT OF ", NUM_IMAGES()," TOTAL IMAGES"
  
END PROGRAM MAIN
