PROGRAM CORR_LENGTH_UNIFORM_RAND
  IMPLICIT NONE
  INTEGER, PARAMETER :: NUM_L = 1000, NUM_R = 1000*NUM_L
  REAL(8), DIMENSION(NUM_R) :: RAND_VAR
  INTEGER :: C,I,L
  REAL(8) :: CORR

  CALL RANDOM_NUMBER(RAND_VAR)
  RAND_VAR = 2.0D0 * RAND_VAR - 1.0D0
  !RAND_VAR = EXP(-RAND_VAR**2)
  OPEN(1,FILE='corr_length.dat')
  DO L = 1, NUM_L
     CORR = 0.0D0
     C = 0
     DO I = 1, NUM_R - NUM_L
        CORR = CORR + RAND_VAR(I) * RAND_VAR(I+L)
        C = C + 1
     END DO
     CORR = CORR / DBLE(C)
     WRITE(1,'(I10,1X,F15.10)')L,CORR
  END DO
  

END PROGRAM CORR_LENGTH_UNIFORM_RAND
