PROGRAM RANDOM_NUMER_DIFFERENCE_DISTRIBUTION
  IMPLICIT NONE
  INTEGER, PARAMETER :: NUM = 10000000
  REAL(8), DIMENSION(NUM) :: ARR1,ARR2,ARR
  REAL(8) :: X,DX,XMIN,XMAX,TERM,DIST
  INTEGER :: I,D,NUMX

  NUMX = 100
  
  CALL RANDOM_NUMBER(ARR1)
  CALL RANDOM_NUMBER(ARR2)

  ARR = ARR1 - ARR2
  

  CALL DLASRT('I',NUM,ARR,I)

  XMIN = ARR(1)
  XMAX = ARR(NUM)
  DX = (XMAX-XMIN)/DBLE(NUMX)
  X = XMIN
  TERM = 0.0D0
  I = 1
  DO WHILE (X <= XMAX)
     D = 0
     DO WHILE (ARR(I) > X-DX .AND. ARR(I) <= X)
        D = D + 1
        I = I + 1
     END DO
     DIST = DBLE(D)!/(XMAX-XMIN)
     DIST = DIST/DBLE(DX*NUM)
     TERM = TERM + DIST*DX
     WRITE(11,'(2(F20.10,1X))')X,DIST
     X = X + DX
  END DO
  PRINT*,TERM



END PROGRAM RANDOM_NUMER_DIFFERENCE_DISTRIBUTION
