PROGRAM GENERATE_POINTS_ON_SHERICAL_SHELL

  IMPLICIT NONE
  REAL(8),PARAMETER :: PI = 4.0D0 * ATAN(1.0D0), TWOPI = 2.0D0 * PI
  INTEGER :: I, NUM_POINTS, NUM_PR
  INTEGER :: NUM_R0, NUM_PHI0, NUM_THETA0
  INTEGER :: NUM_THETA, NUM_PHI
  INTEGER :: IR, IT, IP
  REAL(8) :: AR, THETA, PHI, R1, R2, X(3), VEC(3), SR

  NUM_POINTS = 1000000

  R1 = 0.0D0
  R2 = 1.0D0
  NUM_R0 = 10000
  NUM_PHI0 = 20000
  NUM_THETA0 = 10000

  SR = 0.0D0
  DO IT = 0, NUM_THETA0
     THETA = PI * DBLE(IT)/DBLE(NUM_THETA0)
     SR = SR + SIN(THETA)
  END DO
  PRINT*,INT(SR*NUM_PHI0)
  DO I = 1, NUM_POINTS
     
     !CALL RANDOM_NUMBER(X)

     CALL RANDOM_INTEGER(0,NUM_R0,IR)
     AR = (R2 - R1) * DBLE(IR)/DBLE(NUM_R0) + R1
     NUM_THETA = (AR / R2) * NUM_THETA0
     THETA = PI * DBLE(IT)/DBLE(NUM_THETA)
     CALL RANDOM_INTEGER(0,NUM_PHI0,IP)
     NUM_PHI = SIN(THETA) * (AR/R2) * NUM_PHI0
     CALL RANDOM_INTEGER(0,NUM_PHI,IP)
     PHI = TWOPI * DBLE(IP)/DBLE(NUM_PHI)

     !! METHOD 1 !!
!!$     CALL RANDOM_INTEGER(0,NUM_R0,IR)
!!$     AR = (R2 - R1) * DBLE(IR)/DBLE(NUM_R0) + R1
!!$     CALL RANDOM_INTEGER(-NUM_THETA0,NUM_THETA0,IT)
!!$     THETA = R2 * DBLE(IT)/DBLE(NUM_THETA0)
!!$     THETA = THETA / AR
!!$     THETA = ACOS(THETA)
!!$     CALL RANDOM_INTEGER(0,NUM_PHI0,IP)
!!$     PHI = R2 * DBLE(IP)/DBLE(NUM_PHI0) * TWOPI
!!$     PHI = PHI / AR

     VEC(3) = AR * COS(THETA)
     VEC(2) = AR * SIN(THETA) * COS(PHI)
     VEC(1) = AR * SIN(THETA) * SIN(PHI)

!!$     CALL RANDOM_INTEGER(0,NUM_R0,IR)
!!$     AR = (R2 - R1) * DBLE(IR)/DBLE(NUM_R0) + R1
!!$     NUM_THETA = (AR / R2) * NUM_THETA0
!!$     CALL RANDOM_INTEGER(0,NUM_THETA,IT)
!!$     THETA = PI * DBLE(IT)/DBLE(NUM_THETA)
!!$     NUM_PHI = SIN(THETA) * (AR/R2) * NUM_PHI0
!!$     CALL RANDOM_INTEGER(0,NUM_PHI,IP)
!!$     PHI = TWOPI * DBLE(IP)/DBLE(NUM_PHI)
!!$     VEC(3) = AR * COS(THETA)
!!$     VEC(2) = AR * SIN(THETA) * COS(PHI)
!!$     VEC(1) = AR * SIN(THETA) * SIN(PHI)

     WRITE(1,'(6(F20.10,1X))')VEC,AR,THETA,PHI
  END DO

!!$  DO IR = 0, NUM_R0
!!$     AR = (R2 - R1) * DBLE(IR)/DBLE(NUM_R0) + R1
!!$     DO IT = 0, NUM_THETA0
!!$        THETA = PI * DBLE(IT)/DBLE(NUM_THETA0)
!!$        DO IP = 0, NUM_PHI0
!!$           PHI = TWOPI * DBLE(IP)/DBLE(NUM_PHI0)
!!$           !
!!$           VEC(3) = AR * COS(THETA)
!!$           VEC(2) = AR * SIN(THETA) * COS(PHI)
!!$           VEC(1) = AR * SIN(THETA) * SIN(PHI)
!!$           !
!!$           WRITE(2,'(3(F20.10,1X))')VEC
!!$        END DO
!!$     END DO
!!$  END DO

  DO I = 1, NUM_POINTS
     CALL RANDOM_NUMBER(X)
     AR = ((R2**3 - R1**3) * X(1) + R1**3)**(1.0D0/3.0D0)
     THETA = ACOS(2.0D0 * X(2) - 1.0D0)
     PHI = TWOPI * X(3)
     VEC(3) = AR * COS(THETA)
     VEC(2) = AR * SIN(THETA) * COS(PHI)
     VEC(1) = AR * SIN(THETA) * SIN(PHI)
     WRITE(2,'(3(F20.10,1X))')VEC
  END DO

CONTAINS

  SUBROUTINE RANDOM_INTEGER(N1,N2,NUM)
    !USE MYROUTINES, ONLY : RAN3
    INTEGER, INTENT(IN) :: N1,N2
    INTEGER, INTENT(OUT) :: NUM
    REAL(8) :: TEST
    !CALL RAN3(TEST)
    CALL RANDOM_NUMBER(TEST)
    NUM = FLOOR(TEST * (N2 - N1 + 1) + N1)
    !PRINT*,NUM;PAUSE
  END SUBROUTINE RANDOM_INTEGER

END PROGRAM GENERATE_POINTS_ON_SHERICAL_SHELL
